import os

RESULTS_ROOT = os.path.join(os.path.dirname(__file__), "Results")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "outputs")
RESEARCH_FOCUS_NODE = "salt"

ALLOWED_RELATIONS = {
    "trades_with",
    "extracts_from",
    "taxes",
    "licenses",
    "controls",
    "governs",
    "supplies",
    "depends_on",
    "transports_via",
    "monopolizes",
    "disputes",
    "negotiates_with",
}

COMMODITY_KEYWORDS = {
    "salt",
    "barley",
    "apricot",
    "apricots",
    "fungus",
    "tea",
    "rice",
    "wool",
    "pashm",
    "butter",
    "milk",
    "meat",
    "hair",
    "tsampa",
    "grain",
    "musk",
    "porcelain",
    "leather",
    "cloth",
    "vegetables",
    "sugar",
    "spices",
    "horses",
    "mules",
    "sheep",
    "goats",
    "livestock",
    "yak",
    "yaks",
    "minerals",
    "skins",
    "skins",
    "cashmere",
    "oil",
}

LOCATION_KEYWORDS = {
    "valley",
    "lake",
    "pass",
    "river",
    "plateau",
    "district",
    "province",
    "region",
    "country",
    "border",
    "road",
    "trail",
    "market",
    "village",
    "town",
    "city",
    "state",
    "plateau",
    "mountain",
    "himalaya",
    "tibet",
    "ladakh",
    "kashmir",
    "china",
    "nepal",
    "bhutan",
    "sikkim",
    "amdo",
    "yunnan",
    "sichuan",
    "india",
    "mustang",
    "dolpo",
    "zanskar",
    "leh",
    "rupshu",
    "tso kar",
    "kharnak",
    "dras",
    "karakoram",
    "khaltse",
    "basgo",
    "tukuche",
}

PERSON_INDICATORS = {
    "mr",
    "mrs",
    "ms",
    "dr",
    "bishop",
    "chief",
    "lama",
    "nawab",
    "ruler",
    "king",
    "queen",
    "son",
    "daughter",
    "father",
    "mother",
    "prince",
    "princess",
    "official",
}

BAD_PERSON_TOKENS = {
    "village",
    "villages",
    "world",
    "services",
    "information",
    "accounts",
    "road",
    "roads",
    "change",
    "service",
    "population",
    "modern",
    "movement",
    "supply",
    "goods",
    "prices",
    "market",
    "trail",
    "lake",
    "river",
    "pass",
    "plateau",
    "district",
    "province",
    "region",
    "town",
    "city",
    "state",
    "border",
    "mountain",
    "group",
    "team",
    "people",
    "community",
    "nomads",
    "shepherds",
    "traders",
    "mission",
    "travels",
    "labour",
    "work",
    "history",
    "accounts",
}

KEEP_ENTITY_TYPES = {"PERSON", "GROUP", "COMMODITY", "LOCATION", "CONCEPT"}

ENTITY_ALIASES = {
    "pashm in leh": "pashm",
    "pashm (cashmere)": "pashm",
    "pashm cashmere": "pashm",
    "pashm (cashmere": "pashm",
    "yak": "yak",
    "yaks": "yak",
    "tea bricks": "tea",
    "tea brick": "tea",
    "rupshupa": "rupshu",
    "villagers": "village",
    "for barley": "barley",
    "barley for salt": "barley",
    "grim (naked barley)": "barley",
    "grim naked barley": "barley",
    "barley grain (nas) in zanskar": "barley",
    "salt trade": "salt",
    "salt from tso kar": "salt",
    "tibet's salt lakes": "salt lakes",
}

ENTITY_TYPE_OVERRIDES = {
    "aurangzeb": ("PERSON", 1.0),
    "basgo palace": ("LOCATION", 1.0),
    "barley": ("COMMODITY", 1.0),
    "baltistan": ("LOCATION", 1.0),
    "butter": ("COMMODITY", 1.0),
    "british": ("GROUP", 0.9),
    "caterpillar fungus": ("COMMODITY", 1.0),
    "chang-luk sheep": ("COMMODITY", 1.0),
    "chang-pa": ("GROUP", 1.0),
    "chinese authorities": ("GROUP", 1.0),
    "coarse wool": ("COMMODITY", 1.0),
    "deldan": ("PERSON", 1.0),
    "dried apricots": ("COMMODITY", 1.0),
    "dolpo": ("LOCATION", 1.0),
    "dras": ("LOCATION", 1.0),
    "drogpa": ("GROUP", 1.0),
    "frederic drew": ("PERSON", 1.0),
    "grain": ("COMMODITY", 1.0),
    "hair": ("COMMODITY", 1.0),
    "karakoram": ("LOCATION", 1.0),
    "kharnak": ("LOCATION", 1.0),
    "khaltse": ("LOCATION", 1.0),
    "king of ladakh": ("PERSON", 0.9),
    "kitamura": ("PERSON", 1.0),
    "ladakh": ("LOCATION", 1.0),
    "ladakhi traders": ("GROUP", 1.0),
    "leh area merchants": ("GROUP", 1.0),
    "livestock": ("COMMODITY", 1.0),
    "long dagger": ("COMMODITY", 0.8),
    "meat": ("COMMODITY", 1.0),
    "men": ("GROUP", 0.9),
    "milk": ("COMMODITY", 1.0),
    "missionaries": ("GROUP", 0.9),
    "pack-horses": ("COMMODITY", 1.0),
    "outer hills": ("LOCATION", 0.8),
    "ownership of tso kar": ("CONCEPT", 0.9),
    "pashm": ("COMMODITY", 1.0),
    "porcelain cups": ("COMMODITY", 1.0),
    "rupshu": ("LOCATION", 1.0),
    "salt": ("COMMODITY", 1.0),
    "salt from tso kar": ("COMMODITY", 1.0),
    "salt lakes": ("LOCATION", 0.9),
    "shamma": ("PERSON", 0.8),
    "tea": ("COMMODITY", 1.0),
    "tibet": ("LOCATION", 1.0),
    "tibet baqals": ("GROUP", 1.0),
    "tibetan authorities": ("GROUP", 1.0),
    "tibetan changpas": ("GROUP", 1.0),
    "tibetan herdspeople": ("GROUP", 1.0),
    "tibetan horses": ("COMMODITY", 1.0),
    "tibetan partners": ("GROUP", 1.0),
    "tibetans": ("GROUP", 1.0),
    "tukuche": ("LOCATION", 1.0),
    "village": ("LOCATION", 0.9),
    "yak": ("COMMODITY", 1.0),
    "yarkand breed": ("COMMODITY", 0.8),
    "chang-thang sheep's wool": ("COMMODITY", 0.8),
    "china": ("LOCATION", 1.0),
    "china and tibet": ("LOCATION", 0.8),
    "foodgrains": ("COMMODITY", 0.8),
    "peasant traders": ("GROUP", 0.85),
    "a trade": ("CONCEPT", 0.8),
    "amdowas": ("LOCATION", 0.8),
    "ancient tea horse road": ("COMMODITY", 0.8),
    "bhutanese": ("GROUP", 1.0),
    "buckets of salt water": ("COMMODITY", 0.8),
    "chumey naktsang": ("PERSON", 1.0),
    "dabusun nor": ("LOCATION", 0.8),
    "drokpas": ("GROUP", 0.8),
    "government": ("GROUP", 0.8),
    "himalayan peoples": ("PERSON", 1.0),
    "jada family": ("GROUP", 0.8),
    "ladakhis": ("LOCATION", 0.8),
    "lakes of the changthang": ("LOCATION", 0.8),
    "monasteries": ("LOCATION", 0.8),
    "national cultural heritage": ("GROUP", 1.0),
    "nomads": ("GROUP", 0.85),
    "nomads or drokpas": ("GROUP", 0.85),
    "pe customs house": ("LOCATION", 0.8),
    "people": ("GROUP", 0.85),
    "people of tsakalho": ("GROUP", 0.85),
    "products": ("CONCEPT", 0.8),
    "rice": ("COMMODITY", 0.8),
    "salt from the lakes": ("COMMODITY", 0.8),
    "salt in the lake": ("COMMODITY", 0.8),
    "shepherds": ("GROUP", 0.85),
    "storage facilities": ("CONCEPT", 0.8),
    "the nepalese state": ("LOCATION", 0.8),
    "the subbas": ("GROUP", 0.8),
    "tibetan official": ("LOCATION", 0.8),
    "tibetan salt": ("COMMODITY", 0.8),
    "tibetan women": ("LOCATION", 0.8),
    "tsakalho": ("LOCATION", 0.8),
    "yak butter": ("COMMODITY", 0.8),
    "zhao erfeng": ("PERSON", 1.0),
    "a situation": ("CONCEPT", 0.8),
    "agricultural cycle": ("CONCEPT", 0.8),
    "agriculture": ("CONCEPT", 0.8),
    "area": ("CONCEPT", 0.8),
    "baggage": ("CONCEPT", 0.8),
    "basis": ("CONCEPT", 0.8),
    "begar": ("CONCEPT", 0.8),
    "begar conscription": ("CONCEPT", 0.8),
    "bethus": ("PERSON", 0.7),
    "british officers": ("GROUP", 0.8),
    "british rule": ("CONCEPT", 0.8),
    "cash": ("CONCEPT", 0.8),
    "cash dues": ("CONCEPT", 0.8),
    "cash instead of cloth": ("COMMODITY", 0.8),
    "changes": ("CONCEPT", 0.8),
    "chasralu": ("LOCATION", 0.8),
    "civilisational centres": ("LOCATION", 0.8),
    "clan deity": ("CONCEPT", 0.8),
    "deities": ("CONCEPT", 0.8),
    "deity": ("CONCEPT", 0.8),
    "demands": ("CONCEPT", 0.8),
    "divine functionaries": ("CONCEPT", 0.8),
    "dominant village community": ("LOCATION", 0.8),
    "entire border with the sikh territories": ("LOCATION", 0.8),
    "europeans": ("GROUP", 1.0),
    "gurkhas": ("GROUP", 0.8),
    "gurkhas of nepal": ("LOCATION", 0.8),
    "having no credibility": ("CONCEPT", 0.8),
    "hill state": ("LOCATION", 0.8),
    "hill states": ("LOCATION", 0.8),
    "himalayan peasants": ("LOCATION", 0.8),
    "himalayan population": ("LOCATION", 0.8),
    "hindustan-tibet road": ("LOCATION", 0.8),
    "his patron god": ("CONCEPT", 0.8),
    "i": ("PERSON", 0.5),
    "imprisoned": ("CONCEPT", 0.8),
    "kanets": ("GROUP", 0.8),
    "khash-kanet peasantry": ("GROUP", 0.8),
    "khash-kanet peasants": ("GROUP", 0.8),
    "land revenue": ("CONCEPT", 0.8),
    "land settlements": ("CONCEPT", 0.8),
    "local habitations": ("CONCEPT", 0.8),
    "loggers": ("GROUP", 0.8),
    "logs down the big rivers": ("LOCATION", 0.8),
    "lower hills bordering the plains of punjab": ("LOCATION", 0.8),
    "mahasu": ("LOCATION", 0.9),
    "mandi": ("LOCATION", 0.8),
    "marginal, oppressed people": ("GROUP", 0.85),
    "mountainous areas": ("LOCATION", 0.8),
    "natural products": ("CONCEPT", 0.8),
    "new law": ("CONCEPT", 0.8),
    "obedience": ("CONCEPT", 0.8),
    "obstacles": ("CONCEPT", 0.8),
    "of the states": ("LOCATION", 0.8),
    "outsiders": ("GROUP", 0.8),
    "padam dev gautam": ("PERSON", 0.8),
    "pastoral groups": ("GROUP", 0.8),
    "peasant family": ("GROUP", 0.8),
    "peasantry": ("GROUP", 0.8),
    "peasants": ("GROUP", 0.8),
    "poorzee": ("PERSON", 0.7),
    "prior interventions": ("CONCEPT", 0.8),
    "produce": ("CONCEPT", 0.8),
    "productive resources": ("CONCEPT", 0.8),
    "rana": ("GROUP", 1.0),
    "relations between the state and its subjects": ("LOCATION", 0.8),
    "revenue demand": ("CONCEPT", 0.8),
    "revenue matters in a few hill states": ("LOCATION", 0.8),
    "river sutlej": ("LOCATION", 0.8),
    "ruler of the tract": ("PERSON", 0.7),
    "servile groups": ("GROUP", 0.8),
    "sikhs": ("GROUP", 1.0),
    "simla": ("PERSON", 1.0),
    "special circumstances": ("CONCEPT", 0.8),
    "state forests": ("LOCATION", 0.8),
    "state officials": ("LOCATION", 0.8),
    "state's administration": ("LOCATION", 0.8),
    "surplus": ("CONCEPT", 0.8),
    "sutlej valley": ("PERSON", 1.0),
    "the bethus": ("GROUP", 0.8),
    "the british": ("GROUP", 0.8),
    "the british east india company": ("LOCATION", 0.8),
    "the british government": ("GROUP", 0.8),
    "the corn": ("CONCEPT", 0.8),
    "the crown": ("GROUP", 0.8),
    "the first thing": ("CONCEPT", 0.8),
    "the khumri": ("GROUP", 0.8),
    "the narrow mountain paths": ("LOCATION", 0.8),
    "the raja": ("GROUP", 0.8),
    "the rulers of these hill states": ("LOCATION", 0.8),
    "the state": ("LOCATION", 0.8),
    "the west himalayas": ("LOCATION", 0.8),
    "the western himalayas": ("LOCATION", 0.8),
    "these mountain communities": ("LOCATION", 0.8),
    "this effort": ("CONCEPT", 0.8),
    "those deities": ("CONCEPT", 0.8),
    "through palampur and from leh to kashmir": ("LOCATION", 0.8),
    "tika ruder sen": ("PERSON", 0.8),
    "to be emphasised about himalayan marriage": ("LOCATION", 0.8),
    "to the borders of tibet": ("LOCATION", 0.8),
    "traders and others": ("GROUP", 0.85),
    "traders from the plains": ("GROUP", 0.85),
    "village boundaries": ("LOCATION", 0.8),
    "village deity": ("LOCATION", 0.8),
    "wazeers": ("GROUP", 0.8),
    "with the emergent indian nation": ("LOCATION", 0.8),
    "women": ("GROUP", 0.8),
    "wool of the pastoralists": ("COMMODITY", 0.8),
    "at present": ("CONCEPT", 0.8),
    "consumers": ("GROUP", 0.8),
    "grain for salt": ("COMMODITY", 0.8),
    "grains": ("COMMODITY", 0.8),
    "humlis": ("PERSON", 1.0),
    "indian salt": ("COMMODITY", 0.8),
    "limis": ("GROUP", 1.0),
    "marts": ("LOCATION", 0.8),
    "nepal": ("LOCATION", 0.8),
    "tibetan rock salt": ("COMMODITY", 0.8),
    "traders from two villages": ("GROUP", 0.85),
    "migratory strategy": ("CONCEPT", 0.8),
    "pastoralists": ("GROUP", 0.8),
    "as i descended": ("CONCEPT", 0.8),
    "by solar action": ("CONCEPT", 0.8),
    "donations": ("CONCEPT", 0.8),
    "european plant": ("COMMODITY", 0.8),
    "facts": ("CONCEPT", 0.8),
    "garu": ("LOCATION", 0.8),
    "ladak": ("PERSON", 1.0),
    "loaded men": ("GROUP", 0.8),
    "plants": ("COMMODITY", 0.8),
    "rampur": ("LOCATION", 0.8),
    "saffron": ("COMMODITY", 0.95),
    "snows": ("CONCEPT", 0.8),
    "specimens": ("CONCEPT", 0.8),
    "statements": ("LOCATION", 0.8),
    "strachey": ("PERSON", 0.8),
    "support": ("CONCEPT", 0.8),
    "throughout the year": ("CONCEPT", 0.8),
    "tibetan countries in its neighbourhood": ("LOCATION", 0.8),
}

NOISY_ENTITIES = {
    "complex pattern",
    "harvest time",
    "loads",
    "material base",
    "medical aid to remote villages",
    "nomadic herdspeople of western tibet higher prices",
    "one crop",
    "prized gifts from tibetan highlands",
    "sale",
    "there and in villages along the route",
    "true",
    "valuable corrective",
}

GROUP_KEYWORDS = {
    "authorities",
    "baqals",
    "changpas",
    "herdspeople",
    "merchants",
    "missionaries",
    "nomads",
    "partners",
    "people",
    "shepherds",
    "traders",
    "tibetans",
    "villagers",
}

EDGE_COLOR_BY_RELATION = {
    "trades_with": "#2f8f5b",
    "extracts_from": "#b86b2b",
    "taxes": "#c73e3a",
    "licenses": "#7d5cc6",
    "controls": "#8a4a24",
    "governs": "#315f9f",
    "supplies": "#c28f00",
    "depends_on": "#6f7c85",
    "transports_via": "#2f80c0",
    "monopolizes": "#7f3b3b",
    "disputes": "#d62728",
    "negotiates_with": "#8b6f3d",
}

RELATION_PATTERNS = [
    (
        r"\b(tax|fine|levy|tariff|duty|tribute|excise|collect\s+tax|paid\s+tax)\b",
        "taxes",
    ),
    (
        r"\b(license|licen[sc]e|permit|allow|allowed|grant\s+leave|authorize|authorise)\b",
        "licenses",
    ),
    (r"\b(monopol|dominat|monopolizes)\b", "monopolizes"),
    (
        r"\b(disput|claim|encroach|contest|oppose|fight|attack|seized|seize|claim\s+ownership)\b",
        "disputes",
    ),
    (
        r"\b(negotiate|mediate|agree|settle|mediated|reached\s+agreement|broker)\b",
        "negotiates_with",
    ),
    (r"\b(depend|need|require|rely|reliant)\b", "depends_on"),
    (
        r"\b(transport|carry|haul|convey|ship|move|bring|cart|carted|draw|carry\s+forward)\b",
        "transports_via",
    ),
    (
        r"\b(supply|provide|deliver|offer|furnish|feed|give\s+salt|give\s+tea)\b",
        "supplies",
    ),
    (
        r"\b(extract|collect|remove|withdraw|harvest|mine|gather|fetch|draw|take\s+salt|take\s+from)\b",
        "extracts_from",
    ),
    (
        r"\b(trade|barter|exchange|sell|buy|deal|swap|pay|market|purchase|vend|deal\s+in|trade\s+with)\b",
        "trades_with",
    ),
    (
        r"\b(govern|rule|administer|manage|supervise|oversee|subordinate|subordinated|regulate|control|dominate|claim|authorit)\b",
        "governs",
    ),
    (r"\b(control|dominate|own|possess|claim|rule|manage|administer)\b", "controls"),
]

STOP_WORDS = {
    "the",
    "and",
    "of",
    "in",
    "on",
    "for",
    "to",
    "from",
    "by",
    "as",
    "with",
    "at",
    "a",
    "an",
    "that",
    "this",
    "these",
    "those",
    "is",
    "are",
    "was",
    "were",
    "have",
    "has",
    "had",
    "be",
    "being",
    "been",
    "which",
    "not",
    "but",
    "or",
    "if",
    "their",
    "its",
}

COLOR_BY_TYPE = {
    "PERSON": "#4c72b0",
    "GROUP": "#8172b2",
    "LOCATION": "#55a868",
    "COMMODITY": "#c44e52",
    "CONCEPT": "#937860",
}
SHAPE_BY_TYPE = {
    "PERSON": "dot",
    "GROUP": "dot",
    "LOCATION": "dot",
    "COMMODITY": "dot",
    "CONCEPT": "dot",
}
DEFAULT_COLOR = "#888888"
DEFAULT_SHAPE = "dot"

BAD_COMMODITY_TERMS = {
    "various",
    "other",
    "several",
    "some",
    "many",
    "best",
    "all",
    "more",
    "total",
    "many",
}

BAD_LOCATION_TERMS = {
    "one of",
    "best",
    "valuable",
    "recent",
    "modern",
    "northerly direction",
    "information",
    "insights",
    "famous",
    "ancient",
    "heavy",
    "seasonal",
    "main",
    "general",
    "large",
    "small",
    "other",
    "various",
    "almost",
    "nearby",
    "farther",
    "farther",
    "early",
    "late",
    "central",
    "new",
}
