import os

RESULTS_ROOT = os.path.join(os.path.dirname(__file__), "Results")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "outputs")
RESEARCH_FOCUS_NODE = "salt"

ALLOWED_RELATIONS = {
    "trades_with",
    "extracts_from",
    "taxes",
    "licenses",
    "controls",
    "governs",
    "supplies",
    "depends_on",
    "transports_via",
    "monopolizes",
    "disputes",
    "negotiates_with",
}

COMMODITY_KEYWORDS = {
    "salt",
    "barley",
    "apricot",
    "apricots",
    "fungus",
    "tea",
    "rice",
    "wool",
    "pashm",
    "butter",
    "milk",
    "meat",
    "hair",
    "tsampa",
    "grain",
    "musk",
    "porcelain",
    "leather",
    "cloth",
    "vegetables",
    "sugar",
    "spices",
    "horses",
    "mules",
    "sheep",
    "goats",
    "livestock",
    "yak",
    "yaks",
    "minerals",
    "skins",
    "skins",
    "cashmere",
    "oil",
}

LOCATION_KEYWORDS = {
    "valley",
    "lake",
    "pass",
    "river",
    "plateau",
    "district",
    "province",
    "region",
    "country",
    "border",
    "road",
    "trail",
    "market",
    "village",
    "town",
    "city",
    "state",
    "plateau",
    "mountain",
    "himalaya",
    "tibet",
    "ladakh",
    "kashmir",
    "china",
    "nepal",
    "bhutan",
    "sikkim",
    "amdo",
    "yunnan",
    "sichuan",
    "india",
    "mustang",
    "dolpo",
    "zanskar",
    "leh",
    "rupshu",
    "tso kar",
    "kharnak",
    "dras",
    "karakoram",
    "khaltse",
    "basgo",
    "tukuche",
}

PERSON_INDICATORS = {
    "mr",
    "mrs",
    "ms",
    "dr",
    "bishop",
    "chief",
    "lama",
    "nawab",
    "ruler",
    "king",
    "queen",
    "son",
    "daughter",
    "father",
    "mother",
    "prince",
    "princess",
    "official",
}

BAD_PERSON_TOKENS = {
    "village",
    "villages",
    "world",
    "services",
    "information",
    "accounts",
    "road",
    "roads",
    "change",
    "service",
    "population",
    "modern",
    "movement",
    "supply",
    "goods",
    "prices",
    "market",
    "trail",
    "lake",
    "river",
    "pass",
    "plateau",
    "district",
    "province",
    "region",
    "town",
    "city",
    "state",
    "border",
    "mountain",
    "group",
    "team",
    "people",
    "community",
    "nomads",
    "shepherds",
    "traders",
    "mission",
    "travels",
    "labour",
    "work",
    "history",
    "accounts",
}

KEEP_ENTITY_TYPES = {"PERSON", "GROUP", "COMMODITY", "LOCATION", "CONCEPT"}

ENTITY_ALIASES = {
    "pashm in leh": "pashm",
    "pashm (cashmere)": "pashm",
    "pashm cashmere": "pashm",
    "pashm (cashmere": "pashm",
    "yak": "yak",
    "yaks": "yak",
    "tea bricks": "tea",
    "tea brick": "tea",
    "rupshupa": "rupshu",
    "villagers": "village",
    "for barley": "barley",
    "barley for salt": "barley",
    "grim (naked barley)": "barley",
    "grim naked barley": "barley",
    "barley grain (nas) in zanskar": "barley",
    "salt trade": "salt",
    "salt from tso kar": "salt",
    "tibet's salt lakes": "salt lakes",
}

ENTITY_TYPE_OVERRIDES = {
    "aurangzeb": ("PERSON", 1.0),
    "basgo palace": ("LOCATION", 1.0),
    "barley": ("COMMODITY", 1.0),
    "baltistan": ("LOCATION", 1.0),
    "butter": ("COMMODITY", 1.0),
    "british": ("GROUP", 0.9),
    "caterpillar fungus": ("COMMODITY", 1.0),
    "chang-luk sheep": ("COMMODITY", 1.0),
    "chang-pa": ("GROUP", 1.0),
    "chinese authorities": ("GROUP", 1.0),
    "coarse wool": ("COMMODITY", 1.0),
    "deldan": ("PERSON", 1.0),
    "dried apricots": ("COMMODITY", 1.0),
    "dolpo": ("LOCATION", 1.0),
    "dras": ("LOCATION", 1.0),
    "drogpa": ("GROUP", 1.0),
    "frederic drew": ("PERSON", 1.0),
    "grain": ("COMMODITY", 1.0),
    "hair": ("COMMODITY", 1.0),
    "karakoram": ("LOCATION", 1.0),
    "kharnak": ("LOCATION", 1.0),
    "khaltse": ("LOCATION", 1.0),
    "king of ladakh": ("PERSON", 0.9),
    "kitamura": ("PERSON", 1.0),
    "ladakh": ("LOCATION", 1.0),
    "ladakhi traders": ("GROUP", 1.0),
    "leh area merchants": ("GROUP", 1.0),
    "livestock": ("COMMODITY", 1.0),
    "long dagger": ("COMMODITY", 0.8),
    "meat": ("COMMODITY", 1.0),
    "men": ("GROUP", 0.9),
    "milk": ("COMMODITY", 1.0),
    "missionaries": ("GROUP", 0.9),
    "pack-horses": ("COMMODITY", 1.0),
    "outer hills": ("LOCATION", 0.8),
    "ownership of tso kar": ("CONCEPT", 0.9),
    "pashm": ("COMMODITY", 1.0),
    "porcelain cups": ("COMMODITY", 1.0),
    "rupshu": ("LOCATION", 1.0),
    "salt": ("COMMODITY", 1.0),
    "salt from tso kar": ("COMMODITY", 1.0),
    "salt lakes": ("LOCATION", 0.9),
    "shamma": ("PERSON", 0.8),
    "tea": ("COMMODITY", 1.0),
    "tibet": ("LOCATION", 1.0),
    "tibet baqals": ("GROUP", 1.0),
    "tibetan authorities": ("GROUP", 1.0),
    "tibetan changpas": ("GROUP", 1.0),
    "tibetan herdspeople": ("GROUP", 1.0),
    "tibetan horses": ("COMMODITY", 1.0),
    "tibetan partners": ("GROUP", 1.0),
    "tibetans": ("GROUP", 1.0),
    "tukuche": ("LOCATION", 1.0),
    "village": ("LOCATION", 0.9),
    "yak": ("COMMODITY", 1.0),
    "yarkand breed": ("COMMODITY", 0.8),
    "chang-thang sheep's wool": ("COMMODITY", 0.8),
    "china": ("LOCATION", 1.0),
    "china and tibet": ("LOCATION", 0.8),
    "foodgrains": ("COMMODITY", 0.8),
    "peasant traders": ("GROUP", 0.85),
}

NOISY_ENTITIES = {
    "complex pattern",
    "harvest time",
    "loads",
    "material base",
    "medical aid to remote villages",
    "nomadic herdspeople of western tibet higher prices",
    "one crop",
    "prized gifts from tibetan highlands",
    "sale",
    "there and in villages along the route",
    "true",
    "valuable corrective",
}

GROUP_KEYWORDS = {
    "authorities",
    "baqals",
    "changpas",
    "herdspeople",
    "merchants",
    "missionaries",
    "nomads",
    "partners",
    "people",
    "shepherds",
    "traders",
    "tibetans",
    "villagers",
}

EDGE_COLOR_BY_RELATION = {
    "trades_with": "#2f8f5b",
    "extracts_from": "#b86b2b",
    "taxes": "#c73e3a",
    "licenses": "#7d5cc6",
    "controls": "#8a4a24",
    "governs": "#315f9f",
    "supplies": "#c28f00",
    "depends_on": "#6f7c85",
    "transports_via": "#2f80c0",
    "monopolizes": "#7f3b3b",
    "disputes": "#d62728",
    "negotiates_with": "#8b6f3d",
}

RELATION_PATTERNS = [
    (
        r"\b(tax|fine|levy|tariff|duty|tribute|excise|collect\s+tax|paid\s+tax)\b",
        "taxes",
    ),
    (
        r"\b(license|licen[sc]e|permit|allow|allowed|grant\s+leave|authorize|authorise)\b",
        "licenses",
    ),
    (r"\b(monopol|dominat|monopolizes)\b", "monopolizes"),
    (
        r"\b(disput|claim|encroach|contest|oppose|fight|attack|seized|seize|claim\s+ownership)\b",
        "disputes",
    ),
    (
        r"\b(negotiate|mediate|agree|settle|mediated|reached\s+agreement|broker)\b",
        "negotiates_with",
    ),
    (r"\b(depend|need|require|rely|reliant)\b", "depends_on"),
    (
        r"\b(transport|carry|haul|convey|ship|move|bring|cart|carted|draw|carry\s+forward)\b",
        "transports_via",
    ),
    (
        r"\b(supply|provide|deliver|offer|furnish|feed|give\s+salt|give\s+tea)\b",
        "supplies",
    ),
    (
        r"\b(extract|collect|remove|withdraw|harvest|mine|gather|fetch|draw|take\s+salt|take\s+from)\b",
        "extracts_from",
    ),
    (
        r"\b(trade|barter|exchange|sell|buy|deal|swap|pay|market|purchase|vend|deal\s+in|trade\s+with)\b",
        "trades_with",
    ),
    (
        r"\b(govern|rule|administer|manage|supervise|oversee|subordinate|subordinated|regulate|control|dominate|claim|authorit)\b",
        "governs",
    ),
    (r"\b(control|dominate|own|possess|claim|rule|manage|administer)\b", "controls"),
]

STOP_WORDS = {
    "the",
    "and",
    "of",
    "in",
    "on",
    "for",
    "to",
    "from",
    "by",
    "as",
    "with",
    "at",
    "a",
    "an",
    "that",
    "this",
    "these",
    "those",
    "is",
    "are",
    "was",
    "were",
    "have",
    "has",
    "had",
    "be",
    "being",
    "been",
    "which",
    "not",
    "but",
    "or",
    "if",
    "their",
    "its",
}

COLOR_BY_TYPE = {
    "PERSON": "#4c72b0",
    "GROUP": "#8172b2",
    "LOCATION": "#55a868",
    "COMMODITY": "#c44e52",
    "CONCEPT": "#937860",
}
SHAPE_BY_TYPE = {
    "PERSON": "dot",
    "GROUP": "dot",
    "LOCATION": "dot",
    "COMMODITY": "dot",
    "CONCEPT": "dot",
}
DEFAULT_COLOR = "#888888"
DEFAULT_SHAPE = "dot"

BAD_COMMODITY_TERMS = {
    "various",
    "other",
    "several",
    "some",
    "many",
    "best",
    "all",
    "more",
    "total",
    "many",
}

BAD_LOCATION_TERMS = {
    "one of",
    "best",
    "valuable",
    "recent",
    "modern",
    "northerly direction",
    "information",
    "insights",
    "famous",
    "ancient",
    "heavy",
    "seasonal",
    "main",
    "general",
    "large",
    "small",
    "other",
    "various",
    "almost",
    "nearby",
    "farther",
    "farther",
    "early",
    "late",
    "central",
    "new",
}
